### ISSUE TITLE
Shortcuts in A Secondary Window

### ISSUE THREAD

**Issue by zomp** [ccampbell/mousetrap#247]
Hi, it would be great if Mousetrap would support shortcuts execution from a secondary window (opened via `window.open()` / iframe). Is there a solution for this, please?

User story: Given an application with shortcuts, when a help window is opened, then the shortcuts can be executed even from the help window.

E.g. there could be a function `Mousetrap.bindToThisWindow()` which would serve as a proxy to the original window (`window.opener.Mousetrap.bindToThisWindow()`).

Note, a solution based on the main window is needed (e.g. on `window.opener.Mousetrap`) – the shortcuts can be dynamically changed and it is necessary to reflect the changes in all the application windows.

**Comment by ccampbell** [comment]
Hi @zomp.  I just released version 1.5 of Mousetrap which allows you to bind shortcuts to specific elements.  I am not sure this will be possible natively, but I imagine it could be achieved using a plugin now.

See http://craig.is/killing/mice#wrapping

**Comment by zomp** [comment]
Hi @ccampbell, thanks a lot. Mousetrap is even better now. :-)

Unfortunately my use case is not solved by the new improvements. I need to mirror the same shortcuts (keys and their effects)  in multiple documents (`document` elements of multiple windows). I do not know Mousetrap's internals, but I suppose it could be solved by a method which would link the main window Mousetrap's key handler to a secondary window to listen to shortcuts even there.

Thank you.

**Comment by ccampbell** [comment]
@zomp, yeah.  You should be able to write some sort of manager that creates a couple instances of Mousetrap.  Something like this can maybe get you started:

```javascript
function MousetrapManager() {
    var self = this;
    self.mousetraps = [];
}

MousetrapManager.prototype.bind = function() {
    var args = arguments;
    self.mousetraps.forEach(function(mousetrap) {
        mousetrap.bind.apply(mousetrap, args);
    });
};

var manager = new MousetrapManager();
manager.mousetraps.push(new Mousetrap(document));
manager.mousetraps.push(new Mousetrap(otherWindow));

manager.bind('a', function() {
    console.log('a key pressed');
});
```

I'm not sure about binding to a window though.  I think `document` is safer for cross browser support, but I don't think you have access to `document` when you open a new window from page.

**Comment by zomp** [comment]
Thanks, @ccampbell. That seems to be a good direction. This could be even mentioned in docs as a way of applying the same Mousetrap shortcuts to multiple elements (e.g. forms) and nowhere else.

There is still one problem – my secondary windows are created on demand (this applies even to the forms from the example I mentioned earlier), so Mousetrap would have to be applied on init to the main window and in runtime somehow duplicated to the other windows – AFAIK this is not supported by Mousetrap.

P.S. Do not worry, there is access to `document`: ;-)
* `window.opener.document` – from a secondary window to the main one
* `var myWindow = window.open(...)` → `myWindow.document` – from the main window to the secondary one

**Comment by zomp** [comment]
BTW, my issue could be easily solved by a method, which would translate pressed keys to text (keys → "ctrl+alt+a") in a secondary window and then I could easily trigger that via the main window (`window.opener.Mousetrap.trigger('ctrl+alt+a')`).

This method would also be very useful e.g. for custom shortcuts setting (to let users to set their own shortcuts by pressing whatever they want in a recording area).

I suppose the "keys to text" problem would be even more difficult to implement than other solutions for my use case.

**Comment by ccampbell** [comment]
Ah okay, that makes it a little more complicated.  This is undocumented, but I think it should now be possible to move the bindings over as well.  

I haven't tested this, but when you open the new window you should be able to do this:

```javascript
var originalMousetrap = new Mousetrap(document);
originalMousetrap.bind('a', _handleAKey);

var newMousetrap = new Mousetrap(myWindow.document);
newMousetrap._callbacks = originalMousetrap._callbacks;
newMousetrap._directMap = originalMousetrap._directMap;
```

I don't really intend to document this cause I really do not want those things to be public.  The default global Mousetrap object does not have those properties assigned to it, but if you create your own mousetrap object it will have them.

**Comment by zomp** [comment]
Wow, this seems to be very promising. I will try it and let you know (it will take me a few days).

I have also just found [Record](https://github.com/ccampbell/mousetrap/tree/master/plugins/record) plugin (I do not know how I could overlook it), so it is a backup solution.

Thank you very much, Craig!

**Comment by zomp** [comment]
Hi @ccampbell, it works very well. Thank you!
